$config:

  default.format.processor: 'default'
  default.format.value: '%level %date %args %code'

  ttl:
    default:
      ttl: 50

  production:
    mongo:
      uri: 'mongodb://localhost.loc:27017/dsp-log'
      ttl: 604800
      format:
        name: 'mongo'
        value: '%level, %module, %hostname, %args, %code, %trace, %errors'

  development:
    $extend: production
    mongo:
      uri: 'mongodb://localhost:27017/dsp-log'

  prog12:
    $extend: development
    mongo:
      uri: 'mongodb://localhost:27030/dsp-log'

default:
  all:
    console: true
    syslog: true

production:
  $extend: default
  redfog:
    all,info,debug,error,warn:
      - mongo:
         $extend: :$config.production.mongo
      - console: true

development:
  $extend: production
  redfog:
    all,info,debug,error,warn:
      - mongo:
         $replace: :$config.development.mongo

prog12:
  $extend: development
  redfog:
    all,info,debug,error,warn:
      - mongo:
          $replace: :$config.prog12.mongo
          format:
            name: new
  redfog.bidder.index:
    $extend: redfog
    all,info,debug,error,warn:
      - mongo:
          $extend: :$config.prog12.mongo